---
# Configure beats package.

- name: "Configure {{ beats_package_name }}."
  template:
    src: beats.yml.j2
    dest: "/etc//{{ beats_package_name }}/{{ beats_package_name }}.yml"
  notify: restart beat