---
# tasks file for beats

- include: check.yml

- block:
  - include: redhat.yml
    when: ansible_os_family == "RedHat"
  - include: debian.yml
    when: ansible_os_family == "Debian"
  when: beats_install

- include: config.yml
  when: beats_config != ""